### ISSUE TITLE
'Between' is not working

### ISSUE THREAD

**Issue by bedgren** [jlattimer/CRM-Email-Workflow-Utilities#2]
When using the delete attachment function, if I enter the exact file size it works fine.  But if I enter value for the "Delete >= ..." that is different (and smaller) than the "Delete <= ...." then the attachment does not actually get deleted or removed.
Example:
Attachment= 17,016 bytes
If I put that exact number in for both values it will delete the attachment.
If I enter 16,000 for "Delete >= ...." and 18,000 for the "Delete <= ..." then it will not delete the attachment.
It does not matter if I enter anything in the "Limit to Extensions...." field

Will provide more info/details as requested.

**Comment by bedgren** [comment]
So in thinking about this, maybe there is no 'between'.
Do I need to first run a check condition to see if it is greater that 16,000 bytes, then run a second check condition to see if it is less than 18,000 bytes?

**Comment by jlattimer** [comment]
Yeah - between doesn't really work, either a top end or bottom end range
