### ISSUE TITLE
enable sending email to users attached via connections

### ISSUE THREAD

**Issue by aappddeevv** [jlattimer/CRM-Email-Workflow-Utilities#3]
I have deal teams defined through connections so I need to send an email alert to that team. I did not see that listed so I am opening this issue to request it. It would be great to select either a specific role list or a connection category (which contains multiple roles) by textual role/category name or role/category id.

**Comment by aappddeevv** [comment]
Or maybe send them to a to/cc list based on query, such as a fetchxml query. That may work better.

**Comment by jlattimer** [comment]
Coming in next release
