### ISSUE TITLE
EmailTeam.cs / GetTeamMembers retrieve all team members without statecode

### ISSUE THREAD

**Issue by emregulcan** [jlattimer/CRM-Email-Workflow-Utilities#4]
Dear Jason,
I'm using this solution for CRM 2015 onprem (v2.1.1.0 for CRM 2015).
Today our client send email about "sending email to disabled users", I checked all systemusers and our workflow designs and I find 2 points;
- Microsoft CRM 2015 not remove disabled systemusers from any team
- You get all team members (without state/status code) with [EmailTeam.cs / GetTeamMembers](https://github.com/jlattimer/CRM-Email-Workflow-Utilities/blob/master/LAT.WorkflowUtilities.Email/EmailTeam.cs#L115-L147)

Actually I'm not sure this is about MS CRM or your library, maybe MS CRM 2015 not working as expected, however you should add some conditions when getting team members

**Comment by jlattimer** [comment]
I guess the quick answer would be to remove the users from the teams if they are no longer active. But next  update (fairly soon) I'll add in logic to filter on active users.

**Comment by emregulcan** [comment]
Hi Jason,
Yes we remove users from teams(before posting here) and actually it works however this will be problem for users who not recognized this bug.
(maybe this bug is not yours, as we can guess MS CRM has more known/unknows bugs / buggy features :))

**Comment by jlattimer** [comment]
Fixed in next release
