### ISSUE TITLE
Delete Email Attachments

### ISSUE THREAD

**Issue by jules09235** [jlattimer/CRM-Email-Workflow-Utilities#7]
Hello, 
I have downloaded the solution and have created a Delete Email Attachment Workflow. I went into the properties set the workflow to one email left the rest empty and set note to true. Ran the workflow on the email and nothing happened but my workflow says succeeded. We are using D365 online 8.2. Please see attached SS.
![email with attachments](https://user-images.githubusercontent.com/26904288/38769213-a7ba73b4-3fc4-11e8-8896-ef8c48186b36.PNG)
![workflow succeeded](https://user-images.githubusercontent.com/26904288/38769214-a7d2f20e-3fc4-11e8-9162-4353606686be.PNG)
![workflow properties](https://user-images.githubusercontent.com/26904288/38769215-a7ea2d3e-3fc4-11e8-9dfc-ea9723ff6c8f.PNG)

**Comment by jules09235** [comment]
Any update?

**Comment by DynamicsResources** [comment]
Same for me (Version 9.0.2.197)

**Comment by aseorourke** [comment]
Same for me on v8.2x

**Comment by mmamula** [comment]
It works, but the way the options are written is confusing, also documentation is wrong. If you take a closer look you'll see that by leaving the options empty it will only delete files smaller than 0 bytes and larger than 2,147,483,647 bytes (in other words, nothing :)

This is what works for me:

![image](https://user-images.githubusercontent.com/13455951/45217413-dea79600-b29b-11e8-95f9-f531559452f1.png)

**Comment by owenqh** [comment]
This worked!!! Thank you for sharing!

**Comment by jlattimer** [comment]
@mmamula  Actually the options were set that way on purpose since deleting is a destructive action it's suppose to force people to look at what they are doing.
